# Generated by Django 4.2.7 on 2026-05-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_skills', models.CharField(help_text='Skills separated by commas', max_length=500)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('skill_match_score', models.IntegerField(default=0, help_text='Skill match percentage (0-100)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(limit_choices_to={'role': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.customuser')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['job', 'candidate'], name='application_job_id_ba5711_idx'), models.Index(fields=['status'], name='application_status_1508e0_idx'), models.Index(fields=['-skill_match_score'], name='application_skill_m_e9402f_idx')],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
