# Generated by Django 4.2.7 on 2026-05-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload PDF resume', null=True, upload_to='resumes/'),
        ),
    ]
