# Generated by Django 4.2.7 on 2026-05-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_resume_url_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_excel',
            field=models.FileField(blank=True, help_text='Application details Excel file', null=True, upload_to='applications/excel/'),
        ),
    ]
